config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  root to: "homes#top"
  
  resources :recipes do
    resource :favorites, only: [:create, :destroy]
    resource :cooked_records, only: [:create, :destroy]
    collection do 
      get "search"
    end
  end
  
  resources :articles do
    collection do 
      get "search"
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  belongs_to_active_hash :article_type

  has_one_attached :image
end

app/models/article_type.rb
class ArticleType < ActiveHash::Base
  self.data = [
          {id: 0, name: '選択してください'},
          {id: 1, name: '料理'},
          {id: 2, name: '食材'},
          {id: 3, name: '道具'},
          {id: 4, name: '外食'},
          {id: 5, name: 'つぶやき'},
          {id: 6, name: 'その他'}
]
end

app/models/cooked_record.rb
class CookedRecord < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :user_id, uniqueness: { scope: :recipe_id }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
  validates :user_id, uniqueness: { scope: :recipe_id }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :user, optional: true
  has_one_attached :image
  belongs_to_active_hash :recipe_type
  has_many :recipe_tags, dependent: :destroy
  has_many :tags, through: :recipe_tags, dependent: :destroy

  has_many :favorites, dependent: :destroy
  def favorite_by?(user)
    favorites.where(user_id: user).exists?
  end
  
  has_many :cooked_records, dependent: :destroy
  def cooked_record_by?(user)
    cooked_records.where(user_id: user.id).exists?
  end

  has_one_attached :image

end

app/models/recipe_tag.rb
class RecipeTag < ApplicationRecord
  belongs_to :recipe
  belongs_to :tag
end

app/models/recipe_type.rb
class RecipeType < ActiveHash::Base
  self.data = [
          {id: 0, name: '選択してください'},
          {id: 1, name: 'オリジナル'},
          {id: 2, name: '作ってみた'}
]
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :recipe_tags, dependent: :destroy
  has_many :recipes, through: :recipe_tags, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :recipes

  has_many :favorites, dependent: :destroy
  has_many :favorite_recipes, through: :favorites, source: :recipe

  has_many :cooked_records, dependent: :destroy
  has_many :cooked_record_recipes, through: :cooked_records, source: :recipe

  has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:destroy, :show, :edit, :update]

  def index
    @articles = Article.all.order(created_at: :desc)
  end

  def new
    @article= Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "投稿できたよ！"
      redirect_to articles_path
    else
      render("articles/new")
    end
  end

  def show
  end

  def edit 
  end

  def update
    if @article.update(article_params)
     flash[:notice] = "編集できたよ！"
     redirect_to articles_path
    else
      render("articles/edit")
    end
  end

  def destroy
    @article.destroy
    flash[:notice] = "削除できたよ！"
    redirect_to articles_path
  end

  def search
      @articles = Article.where(article_type_id: params[:article_type_id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :image, :article_type_id).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

end

app/controllers/cooked_records_controller.rb
class CookedRecordsController < ApplicationController
  before_action :authenticate_user!

  def create
    @recipe = Recipe.find(params[:recipe_id])
    cooked_record = @recipe.cooked_records.new(user_id: current_user.id)
    if cooked_record.save
      redirect_to request.referer
    else
      redirect_to request.referer
    end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    cooked_record = @recipe.cooked_records.find_by(user_id: current_user.id)
    if cooked_record.present?
        cooked_record.destroy
        redirect_to request.referer
    else
        redirect_to request.referer
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @recipe = Recipe.find(params[:recipe_id])
    # favorite = @recipe.favorites.new(user_id: current_user.id)
    @favorite = Favorite.create(user_id: current_user.id, recipe_id: @recipe.id)
    redirect_to request.referer
    # if favorite.save
    #   redirect_to request.referer
    # else
    #   redirect_to request.referer
    # end
  end

  def destroy
    @recipe = Recipe.find(params[:recipe_id])
    # favorite = @recipe.favorites.find_by(user_id: current_user.id)
    @favorite = Favorite.find_by(user_id: current_user.id, recipe_id: @recipe.id)
    @favorite.destroy
    redirect_to request.referer
    # if favorite.present?
    #     favorite.destroy
    #     redirect_to request.referer
    # else
    #     redirect_to request.referer
    # end
  end
end


  # def create
  #   favorite = current_user.favorites.build(recipe_id: params[:recipe_id])
  #   favorite.save!
  #   redirect_to recipes_path, success: t('.flash.favorite')
  # end

  # def destroy
  #   current_user.favorites.find_by(recipe_id: params[:recipe_id]).destroy!
  #   redirect_to recipes_path, success: t('.flash.not_favorite')
  # end
# end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @recipes = Recipe.order(created_at: :desc).limit(1)
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
   before_action :set_recipe, only: [:destroy, :show, :edit, :update]
  
  def index
    @recipes = Recipe.all.order(created_at: :desc)
    # if params[:reciep_type_id].present?
    #     @recipes = RecipeType.find(params[:recipe_type_id]).recipes
    # else
    #     @recipes = Recipe.all.order(created_at: :desc)
    # end
    # @recipes = params[:reciep_type_id].present? ? RecipeType.find(params[:recipe_type_id]).recipes : Recipe.all
  end

  def new
    @recipe = Recipe.new
  end
  
  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      flash[:notice] = "投稿できたよ！"
      redirect_to root_path
    else
      render("recipes/new")
    end
  end

  def show
  end

  def edit 
  end

  def update
    if @recipe.update(recipe_params)
     flash[:notice] = "編集できたよ！"
     redirect_to root_path
    else
      render("recipes/edit")
    end
  end

  def destroy
    @recipe.destroy
    flash[:notice] = "削除できたよ！"
    redirect_to root_path
  end

  def search
    if params[:q]
      @q = Recipe.ransack(params[:q])
      @recipes = @q.result(distinct: true)
    elsif params[:tag_id]
      @tag = Tag.find(params[:tag_id])
      @recipes = @tag.recipes.all
    end
  end


  private
  def recipe_params
    params.require(:recipe).permit(:title, :subtitle, :ingredient, :method, :point, :recipe_type_id, :image, tag_ids: []).merge(user_id: current_user.id)
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  private

  def users_params
    params.require(:user).permit(:nickname, :email, :encrypted_password).merge(user_id: current_user.id)
  end

  def set_user
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/cooked_records_helper.rb
module CookedRecordsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<br>
<br>
<br>

<%= form_with model: article, local: true do |f| %>
タイトル
<%= f.text_field :title, value: article.title %>
<br>
画像
<%= f.file_field :image %>
<br>
テキスト
<%= f.text_area :text, value: article.text %>
<br>
コラムタイプ
<%= f.collection_select(:article_type_id, ArticleType.all, :id, :name, {}, {class:"article-type-select"}) %>

<br>
<%= f.submit "送信！"%>
<% end %>

app/views/articles/edit.html.erb
<%= render partial: 'recipes/header'%>

<h1>編集ページ</h1>
<div class = "error">
  <% @article.errors.full_messages.each do |message|%>
    <%= message %>
  <% end %>
</div>
<br>
<%= render partial: 'form', locals: {article: @article, url: article_path, method: :patch} %>
<%= button_to "戻る", articles_path, method: :get %>

app/views/articles/index.html.erb
<%= render partial: 'recipes/header'%>

<div class ="container">
  <div class = "main-wrapper">    
      <div class = "list">
        <% @articles.each do |article| %> 
          <%= link_to article_path(article.id), class: "no-line" do %>
            <div class ="index content">
              <div class = "index-image-type">
                <%= image_tag article.image.variant(resize:'400x400').processed, class: "index-image" if article.image.attached? %>
                <p><%= article.article_type.name %></p>
              </div>
              <h1 class="index-title"><%= article.title %></h1>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= link_to "新規投稿", "/articles/new"%>
  </div>

  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>

app/views/articles/new.html.erb
<%= render partial: 'recipes/header'%>

<h1>新規投稿画面</h1>
 <% @article.errors.full_messages.each do |message|%>
  <%= message %>
 <% end %>

<%= render partial: 'form', locals: {article: @article, model: @article} %>

<%= button_to "コラム一覧", articles_path, method: :get %>

app/views/articles/search.html.erb
<%= render partial: 'recipes/header'%>

<div class ="container">
  <div class = "main-wrapper">    
      <div class = "article-list">
        <% @articles.each do |article| %> 
          <div class ="article">
            <div class = "article-image-type">
              <%= image_tag article.image.variant(resize:'400x400').processed if article.image.attached? %>
              <p><%= article.article_type.name %></p>
            </div>
            <%= link_to article.title, "/articles/#{article.id}", method: :get, class: "article-title"%>
          </div>
        <% end %>
      </div>
      <%= link_to "新規投稿", "/articles/new"%>
  </div>

  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>

app/views/articles/show.html.erb
<%= render partial: 'recipes/header'%>

<div class ="container">
  <div class = "main-wrapper">

        <div class = "show">
            <div class = "show-title">   
            <%= @article.title %>
            </div>
            
            <div class = "show-image-type">
                <%= image_tag @article.image.variant(resize:'600x600').processed, class: "show-image" if @article.image.attached? %>
                <br>
                <p><%= @article.article_type.name %></p>
            </div> 
            
            <div class = "article-text">
            <%= @article.text %>
            </div>
        </div>
  </div>

  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>

<ul>
    <%= button_to "編集", "/articles/#{@article.id}/edit", method: :get %>
    <%= button_to "削除", "/articles/#{@article.id}", method: :delete %>
    <%= button_to "戻る", articles_path, method: :get %>
</ul>

app/views/cooked_records/create.html.erb
<h1>CookedRecords#create</h1>
<p>Find me in app/views/cooked_records/create.html.erb</p>

app/views/cooked_records/destroy.html.erb
<h1>CookedRecords#destroy</h1>
<p>Find me in app/views/cooked_records/destroy.html.erb</p>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/recipes/_footer.html.erb
<div class = "footer">
  --- Please follow :D ---
  <br>
  <a href="https://twitter.com/woyovt6blclujse" class="fa fa-twitter fa-2x twitter" aria-hidden="true"></a>
  <a href="https://www.instagram.com/kazuya_no_gohan/" class="fa fa-instagram fa-2x instagram" aria-hidden="true"></a>
</div>

app/views/recipes/_form.html.erb
<br>
<br>
<br>
<%= form_with model: recipe, local: true do |f| %>

タイトル
<%= f.text_field :title, value: recipe.title %>
<br>
サブタイトル
<%= f.text_field :subtitle, value: recipe.subtitle %>
<br>
画像
<%= f.file_field :image %>
<br>
タグ
<div class='form-group'>
  <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
    <div class='form-check'>
      <%= tag.label class: 'form-check-label' do %>
        <%= tag.check_box class: 'form-check-input' %>
        <%= tag.text %>
      <% end %>
    </div>
  <% end %>
</div>
<br>
材料
<%= f.text_area :ingredient, value: recipe.ingredient %>
<br>
手順
<%= f.text_area :method, value: recipe.method %>
<br>
ポイント
<%= f.text_area :point, value: recipe.point %>
<br>
レシピタイプ
<%= f.collection_select(:recipe_type_id, RecipeType.all, :id, :name, {}, {class:"recipe-type-select"}) %>

<%= f.submit "送信！"%>
<% end %>

app/views/recipes/_header.html.erb
<div class = "header">
  <%= link_to "Kazuya no gohan", root_path, {method: :get, class: "home-link"} %>
  <%= link_to "Recipe", recipes_path, {class: "recipe-link"} %>
  <%= link_to "Column", articles_path, {method: :get, class: "column-link"} %>
  <div class = "header-name">
    <% if user_signed_in? %>
      <%# <div class = "hello">こんにちは　</div> %>
      <%# <div class = "current-user"><%= current_user.nickname %>
      <%# </div>  %>
      <%# <div class = "sann">　さん　/　</div> %>
      <%= link_to "my page", user_path(current_user), {method: :get, class: "mypage"} %>
      <div class = "slash"> / </div>
      <%= link_to "logout",destroy_user_session_path, {method: :delete, class: "logout"} %>
    <% else %>
      <%= link_to "login",new_user_session_path, {class: "login"} %>
      <%# <%= link_to "新規登録",new_user_registration_path, {method: :get, class: "user-registration"} %>
    <% end %>
  </div>
</div>

app/views/recipes/_second_header.html.erb
<div class = "second-header">
  <%= link_to "Kazuya no gohan", root_path, {method: :get, class: "home-link"} %>
  <%= link_to "Recipe", recipes_path, {class: "recipe-link"} %>
  <%= link_to "Column", articles_path, {method: :get, class: "column-link"} %>
  <div class = "header-name">
    <% if user_signed_in? %>
      <%# <div class = "hello">こんにちは　</div> %>
      <%# <div class = "current-user"><%= current_user.nickname %>
      <%# </div>  %>
      <%# <div class = "sann">　さん　/　</div> %>
      <%= link_to "my page", user_path(current_user), {method: :get, class: "mypage"} %>
      <div class = "slash"> / </div>
      <%= link_to "logout",destroy_user_session_path, {method: :delete, class: "logout"} %>
    <% else %>
      <%= link_to "login",new_user_session_path, {class: "login"} %>
      <%# <%= link_to "新規登録",new_user_registration_path, {method: :get, class: "user-registration"} %>
    <% end %>
  </div>
</div>

app/views/recipes/_sidebar.html.erb
<div class="search-title">search</div>

<div class = "search-container">
  <%= search_form_for Recipe.ransack(params[:q]), url: search_recipes_path do |f| %>
    <%= f.label :title_or_subtitle_or_ingredient, "--Keyword--", {class: "search-menu"} %>
    <br>
    <%= f.search_field :title_or_subtitle_or_ingredient_cont, placeholder: "食材や料理名でレシピ検索", class: "search-field" %>
    <%= f.button type: 'submit', class: "search-button" do %>
      <span class="fa fa-search fa-1x"></span>
    <% end %>

    <br>
    <%= f.label :recipe_type_id_eq, "recipe type" %>
    <%= f.radio_button :recipe_type_id_eq, '', {class: "recipe-type-select", :checked => true} %>指定なし
    <%= f.radio_button :recipe_type_id_eq, 1, {class: "recipe-type-select"} %>オリジナル
    <%= f.radio_button :recipe_type_id_eq, 2, {class: "recipe-type-select"}%>作ってみた
  <% end %>

  <div class="search-menu">--recipe category--</div>
    <ul>
      <li><%= link_to "和食", search_recipes_path(tag_id: 1) %></li>
      <li><%= link_to "洋食", search_recipes_path(tag_id: 2) %></li>
      <li><%= link_to "中華", search_recipes_path(tag_id: 3) %></li>
      <li><%= link_to "多国籍",search_recipes_path(tag_id: 4) %></li>
      <br>
      <li><%= link_to "オードブル", search_recipes_path(tag_id: 5) %></li>
      <li><%= link_to "スープ", search_recipes_path(tag_id: 6) %></li>
      <li><%= link_to "メイン", search_recipes_path(tag_id: 7) %></li>
      <li><%= link_to "パスタ", search_recipes_path(tag_id: 8) %></li>
      <li><%= link_to "リゾット", search_recipes_path(tag_id: 9) %></li>
      <li><%= link_to "デザート", search_recipes_path(tag_id: 10) %></li>
    </ul>


  <div class="search-menu">--column category--</div>
    <ul>
      <li><%= link_to "料理", search_articles_path(article_type_id: 1) %></li>
      <li><%= link_to "食材", search_articles_path(article_type_id: 2) %></li>
      <li><%= link_to "道具", search_articles_path(article_type_id: 3) %></li>
      <li><%= link_to "外食", search_articles_path(article_type_id: 4) %></li>
      <li><%= link_to "つぶやき", search_articles_path(article_type_id: 5) %></li>
      <li><%= link_to "その他", search_articles_path(article_type_id: 6) %></li>
    </ul>
</div>

app/views/recipes/edit.html.erb
<%= render partial: 'recipes/header'%>

<h1>編集ページ</h1>
<div class = "error">
  <% @recipe.errors.full_messages.each do |message|%>
    <%= message %>
  <% end %>
</div>
<br>
<%= render partial: 'form', locals: {recipe: @recipe, url: recipe_path, method: :patch} %>
<%= button_to "戻る", recipes_path, method: :get %>

app/views/recipes/index.html.erb
<%= render partial: 'recipes/header'%>

<div class ="container">
  <div class = "main-wrapper">

    <div class = "list">
      <% @recipes.each do |recipe| %>
        <%= link_to recipe_path(recipe.id), class: "no-line" do %>
          <div class = "index content">
            <div class = "index-image-type">
              <%= image_tag recipe.image.variant(resize:'400x400').processed, class: "index-image" if recipe.image.attached? %>
              <p><%= recipe.recipe_type.name %></p>
            </div>
            <h1 class="index-title"><%= recipe.title %></h1>
            <div class = "index-tag">
              <% recipe.tags.each do |tag| %>
                <span class= 'tag-name'><%= tag.name %></span>
              <% end %>
            </div>
            <div class = "index-subtitle"><%= recipe.subtitle %></div>
          </div>
        <% end %>
      <% end %>
    </div>
    <%= link_to "新規投稿", "/recipes/new"%>
  </div>

  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render partial: 'recipes/header'%>

<h1>新規投稿画面</h1>
 <% @recipe.errors.full_messages.each do |message|%>
  <%= message %>
 <% end %>

<%= render partial: 'form', locals: {recipe: @recipe, model: @recipe} %>

<%= button_to "レシピ一覧", recipes_path, method: :get %>

app/views/recipes/search.html.erb
<%= render partial: 'recipes/header'%>

<div class ="container">
  <div class = "main-wrapper">
    <br>
    <br>

    <div class = "recipe-list">
      <% @recipes.each do |recipe| %>
        <%= link_to recipe_path(recipe.id) do %>
          <div class = "recipe content">
            <div class = "recipe-image-type">
              <%= image_tag recipe.image.variant(resize:'400x400').processed if recipe.image.attached? %>
              <p><%= recipe.recipe_type.name %></p>
            </div>
            <h1 class="recipe-title-new"><%= recipe.title %></h1>
            <br>
            <div class = "recipe-subtitle">
              <%= recipe.subtitle %>
              <br>
            </div>
            <div class = "recipe-favorite">
            <% if recipe.favorite_by?(current_user) %>
              <%= link_to recipe_favorites_path(recipe_id: recipe.id), method: :delete do %>
                <i class="fa fa-heart fa-2x unlike-btn" aria-hidden="true"></i>
              <% end %>
            <% else %>
              <%= link_to recipe_favorites_path(recipe_id: recipe.id), method: :post do %>
                <i class="fa fa-heart fa-2x like-btn" aria-hidden="true"></i>
              <% end %>
            <% end %>
            </div>
            <div class = "recipe-cooked-record">
              <% if recipe.cooked_record_by?(current_user) %>
                  <%= link_to recipe_cooked_records_path(recipe_id: recipe.id), method: :delete do %>
                    <i class="fa fa-calendar-check-o fa-2x uncheck-btn" aria-hidden="true"></i>
                  <% end %>
              <% else %>
                  <%= link_to recipe_cooked_records_path(recipe_id: recipe.id), method: :post do %>
                    <i class="fa fa-calendar-check-o fa-2x check-btn" aria-hidden="true"></i>
                  <% end %>
              <% end %>
              <br>
            </div>
            <div class = "recipe-tag">
              <% recipe.tags.each do |tag| %>
                <span class= 'tag-name'><%= tag.name %></span>
              <% end %>
              <br>
              <br>
            </div>         
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>

app/views/recipes/show.html.erb
<%= render partial: 'recipes/header'%>

<div class ="container">
  <div class = "main-wrapper">

    <div class = "show">
        <div class = "show-title">
          <%= @recipe.title %>
        </div>

        <div class = "show-image-type">
          <%= image_tag @recipe.image.variant(resize:'600x600').processed, class: "show-image" if @recipe.image.attached? %>
          <p><%= @recipe.recipe_type.name %></p>
        </div>

        <div class = "show-tag">
          <% @recipe.tags.each do |tag| %>
              <span class= 'tag-name'><%= tag.name %></span>
          <% end %>
          <br>
        </div>
        
        <div class = "recipe-favorite-and-cooked-record">
            <div class = "recipe-symbol">
              <% if @recipe.favorite_by?(current_user) %>
                    <%= link_to recipe_favorites_path(recipe_id: @recipe.id), class: "no-line", method: :delete do %>
                      <span class="fa fa-heart fa-1x unlike-btn" aria-hidden="true"></span><span class="margin-10">お気に入り</span>
                    <% end %>
              <% else %>
                    <%= link_to recipe_favorites_path(recipe_id: @recipe.id), class: "no-line", method: :post do %>
                      <span class="fa fa-heart fa-1x like-btn" aria-hidden="true"></span><span class="margin-10">お気に入り</span>
                    <% end %>
              <% end %>
            </div>

            <div class = "recipe-symbol">
              <% if @recipe.cooked_record_by?(current_user) %>
                    <%= link_to recipe_cooked_records_path(recipe_id: @recipe.id), class: "no-line", method: :delete do %>
                      <span class="fa fa-calendar-check-o fa-1x uncheck-btn" aria-hidden="true"></span><span class="margin-10">作ったログ</span>
                    <% end %>
              <% else %>
                    <%= link_to recipe_cooked_records_path(recipe_id: @recipe.id), class: "no-line", method: :post do %>
                      <span class="fa fa-calendar-check-o fa-1x check-btn" aria-hidden="true"></span><span class="margin-10">作ったログ</span>
                    <% end %>
              <% end %>
            </div>
        </div>    

        <div class = "show-subtitle">
          <%= @recipe.subtitle %>
        </div>
        <br>
        <%# <%= @recipe.created_at.strftime('%Y年 %m月 %d日') %> 
        <br> 
        材料
        <br>
        <table>
          <tr><!-- 行1（見出し）-->
            <th>食材</th> <th>分量</th>
          </tr>
          <% @recipe.ingredient.split("\r\n").each do |ingredient|%>
            <tr>
              <% ingredient.squish.split(" ").each do |igd|%>
                <td><%= igd %></td>
              <% end %>
            </tr>
          <% end %>
        </table>


        <br>
        作り方
        <br>
        <%= simple_format(@recipe.method) %>


        <br>
        ポイント
        <br>
        <%= @recipe.point %>

      <br>
    </div>

  </div>
    
  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>

<ul>
    <%= button_to "編集", "/recipes/#{@recipe.id}/edit", method: :get %>
    <%= button_to "削除", "/recipes/#{@recipe.id}", method: :delete %>
    <%= button_to "戻る", recipes_path, method: :get %>
</ul>

app/views/users/show.html.erb
<%= render partial: 'recipes/header'%>
<div class ="container">
  <div class = "main-wrapper">
    Hello
    <%= current_user.nickname %>さん
 　お気に入り一覧
 　作った記録一覧
 　閲覧履歴
  </div>

  <div class="sidebar">
    <%= render partial: 'recipes/sidebar' %>
  </div>
</div>